eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 10000
server:
  port: 8080

spring:
  application:
    name: zuul
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 8e7167d91e93a417068c
            clientSecret: bd30b4e2b811aba1b73bc5fcd7c60a3925259d67

zuul:
  ignored-services: '*'
  #sensitiveHeaders: Cookie,Set-Cookie
  routes:
    config:
      path: /config/**
      service-id: config-server
    movie:
      path: /movie/**
      service-id: movie-data-collector
    security:
      path: /sec/**
      service-id: security-server
    test:
      path: /test/**
      service-id: test
    user-service:
      path: /user-service/**
      service-id: user-service
    rating-service:
      path: /rating-service/**
      service-id: rating-service
    feedback-service:
      path: /feedback-service/**
      service-id: feedback-service
    
    explore:
      path: /explore/**
      service-id: trainingservice
      
    db:
      path: /db/**
      service-id: trainingservice
#
