eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 10000
server:
  port: 8080
spring:
  application:
    name: zuul-proxy

zuul:
  ignored-services: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    config:
      path: /config/**
      service-id: config-server
    movie:
      path: /movie/**
      service-id: movie-data-collector
    security:
      path: /sec/**
      service-id: security-server
    test:
      path: /test/**
      service-id: test
    user-service:
      path: /user-service/**
      service-id: user-service

security:
  oauth2:
    resource:
      jwt:
        key-value: 123
